### ISSUE TITLE
Sample codes does not work

### ISSUE THREAD

**Issue by bioinfolabmu** [ComputationalRegulatoryGenomicsICL/TFBS#2]
Hi, I have installed your package TFBS. However, when I run the given sample codes, I got the following error:

mubil@bioinfo-80[examples] perl script1.pl                                                                                     [ 4:09PM]
Use of uninitialized value $Bio::DB::NCBIHelper::HOSTBASE in concatenation (.) or string at /usr/share/perl5/Bio/DB/Query/GenBank.pm line 103.
Use of uninitialized value $Bio::DB::NCBIHelper::HOSTBASE in concatenation (.) or string at /usr/share/perl5/Bio/DB/Query/GenBank.pm line 104.
Can't call method "search_seq" on an undefined value at script1.pl line 7.

What is inside script1.pl
# !/usr/bin/env perl  -w

use Bio::DB::GenBank; 
use TFBS::DB::TRANSFAC; 
my $seq = Bio::DB::GenBank->new()->get_Seq_by_acc('AF100993'); 
my $db = TFBS::DB::TRANSFAC->connect(-accept_conditions => 1); 
my $pwm = $db->get_Matrix_by_ID('V$CEBPA_01','PWM'); 
my $siteset = $pwm->search_seq(-seqobj=>$seq, -threshold=>"80%"); 
print $siteset->GFF();

Any help will be highly appreciated.

**Comment by ge11232002** [comment]
Hi, this is because the API of querying TRANSFAC has been changed. But TFBS is not under active development and we only do bug fix to it. Please migrate to TFBSTools(http://www.bioconductor.org/packages/release/bioc/html/TFBSTools.html), which is successor of TFBS and also expands TFBS.

Ge
